version: '3.8'
services:
  backend:
    image: backend
    ports:
      - "3000:3000"
    networks:
      - app_network
      
  frontend:
    image: frontend
    ports:
      - "80:80"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge