version: '3.8'
services:
  backend:
    build: ./Node
    ports:
      - "3000:3000"

  frontend:
    image: frontend
    ports:
      - "80:80"

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: